#!/bin/sh

NAME="ecomarket"
ADDRESS='127.0.0.1'
PYTHON="/home/ubuntu/venvs/$NAME/bin/python"
GUNICORN="/home/ubuntu/venvs/$NAME/bin/gunicorn_django"
PROJECTLOC="/home/ubuntu/webapps/$NAME/"
MANAGELOC="$PROJECTLOC/manage.py"
DEFAULT_ARGS="--workers=4 --daemon --bind=$ADDRESS:"
BASE_CMD="$GUNICORN $DEFAULT_ARGS"

PORT='8000'
PIDFILE="/tmp/ecomarket.pid"

start_server () {
  if [ -f $1 ]; then
    #pid exists, check if running
    if [ "$(ps -p `cat $1` | wc -l)" -gt 1 ]; then
       echo "Server already running on ${ADDRESS}:${2}"
       return
    fi
  fi
  cd $PROJECTLOC
  echo "starting ${ADDRESS}:${2}"
  $BASE_CMD$2 --pid=$1
}

stop_server (){
  if [ -f $1 ] && [ "$(ps -p `cat $1` | wc -l)" -gt 1 ]; then
    echo "stopping server ${ADDRESS}:${2}"
    kill -9 `cat $1`
    rm $1
  else
    if [ -f $1 ]; then
      echo "server ${ADDRESS}:${2} not running"
    else
      echo "No pid file found for server ${ADDRESS}:${2}"
    fi
  fi
}

case "$1" in
'start')
  start_server $PIDFILE $PORT
  ;;
'stop')
  stop_server $PIDFILE $PORT
  ;;
'restart')
  stop_server $PIDFILE $PORT
  sleep 5
  start_server $PIDFILE $PORT
  # making sure it starts
  sleep 5
  start_server $PIDFILE $PORT
  # making sure it starts
  sleep 5
  start_server $PIDFILE $PORT
  ;;
*)
  echo "Usage: $0 { start | stop | restart }"
  ;;
esac

exit 0