import os

from django.core.management.base import NoArgsCommand
from django.template.loader import render_to_string

from marketplace.models import Category


class Command(NoArgsCommand):

    static_template_name = "fragments/static_category_dropdown.html"
    help = ("Update the static categories template (%s)" % (
                static_template_name))

    def render_template(self):
        template_name = "main/generate_static_category_dropdown.html"
        auto_generated_notice = """\
{% comment %}
This file is automatically generated. To edit it, change the template
'main/generate_static_category_dropdown.html' and run
'manage.py update_static_categories'
{% endcomment %}"""
        content =  render_to_string(template_name, {
            "top_level_categories": Category.objects.get_toplevel(),
        })
        return "%s\n%s" % (auto_generated_notice, content)

    def handle_noargs(self, **kwargs):
        static_template_name = os.path.join("templates",
                                            self.static_template_name)
        with open(static_template_name, "w") as fh:
            fh.write(self.render_template())
        self.stdout.write("Template written to %s\n" % static_template_name)
